// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Commands sidebar for Linux commands
  commandsSidebar: [{type: 'autogenerated', dirName: 'commands'}],

  // Distributions sidebar for Linux distributions
  distrosSidebar: [{type: 'autogenerated', dirName: 'distros'}],

  // Tutorials sidebar for Linux tutorials
  tutorialsSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
